
included:
  - MyUniverse
  - weak_delegate
  - unused_declaration

disabled_rules:
  - file_length
  - trailing_whitespace
  - function_body_length
  - identifier_name

excluded:
  - Pods

line_length: 250
